basePath: /sa/v1
definitions:
  auth.AuthReq:
    properties:
      password:
        description: Password
        type: string
      username:
        description: User name
        type: string
    required:
    - password
    - username
    type: object
  auth.Token:
    properties:
      token:
        description: User token used to be authenticated
        type: string
      userName:
        description: User name
        type: string
    type: object
  auth.TokenResp:
    properties:
      token:
        $ref: '#/definitions/auth.Token'
    type: object
  cmd.CmdRun:
    properties:
      command:
        description: Command to run
        type: string
      cwd:
        description: Specifies the current working directory for command execution
        type: string
      envs:
        description: List of environment variables
        items:
          type: string
        type: array
    required:
    - command
    type: object
  cmd.CmdRunResponse:
    properties:
      output:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact:
    email: williamlu9@gmail.com
    name: Schedrestd Support
    url: http://teraproc.com/
  description: '{{escape .Description}}'
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /cmd/run:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer <Add token here>
        description: Token with Bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Run a command
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/cmd.CmdRun'
      produces:
      - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/cmd.CmdRunResp'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        '401':
          description: Unauthorized user
          schema:
            $ref: '#/definitions/response.Response'
        '403':
          description: Permission denied
          schema:
            $ref: '#/definitions/response.Response'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Run a command
      tags:
      - cmd
  /file/download/{file_name}:
    get:
      description: 'Example upload request:

        curl -X GET -H "Authorization: Bearer $TOKEN" "http://localhost:8088/sa/v1/file/download/testfile"
        > ./testfile'
      parameters:
      - default: Bearer <Add token here>
        description: Token with Bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: file_name
        in: path
        name: file_name
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/file.FileResp'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        '401':
          description: Unauthorized user
          schema:
            $ref: '#/definitions/response.Response'
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Download a file from user home directory
      tags:
      - file
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      description: 'Example upload request:

        curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data"
        -F "file=@/shared/testfile" "http://localhost:8088/sa/v1/file/upload"'
      parameters:
      - default: Bearer <Add token here>
        description: Token with Bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: upload file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/file.FileResp'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        '401':
          description: Unauthorized user
          schema:
            $ref: '#/definitions/response.Response'
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Upload a file to user home directory
      tags:
      - file
  /login:
    post:
      description: Logs user into the system
      parameters:
      - description: Authenticate request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.AuthReq'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/auth.TokenResp'
        '400':
          description: Invalid username/password supplied
          schema:
            $ref: '#/definitions/response.Response'
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'

