package common

// ConfigFileName ...
const ConfigFileName = "schedrestd"

// ConfigType ...
const ConfigType = "yaml"

// HostName ...
const HostName = "HOSTNAME"

// Fatal ...
const Fatal = "fatal"

// Error ...
const Error = "error"

// Warn ...
const Warn = "warn"

// Info ...
const Info = "info"

// Debug ...
const Debug = "debug"

// LoggerName ...
const LoggerName = "alogger"

// TokenHeader ...
const TokenHeader = "Authorization"

// UserHeader ...
const UserHeader = "user"

// NoTokenMsg ...
const NoTokenMsg = "Missing authentication token. Login required"

// ExpiredMsg ...
const ExpiredMsg = "Token expired. Login required"

// BoltDBName ...
const BoltDBName = "schedrestd.db"

// BoltDBJWTTable ...
const BoltDBJWTTable = "jwt"

// SuccessMsg ...
const SuccessMsg = "Success"

//SourceCmd
const SourceCmd = "source /etc/profile"
